### ISSUE TITLE
FTP connections through URLConnection fail from within private network / firewall

### ISSUE THREAD

**Issue by sheridancbio** [cBioPortal/pdb-annotation#14]
Code in PdbScriptsPipelineRunCommand.java may attempt to access files through a URLConnection object from the standard java library. If the url specifies the "ftp:" protocol, and if the program is running inside a private network or behind a firewall, the data connection for the ftp transfer may fail.

Luckily, all URLs in use currently come from servers which offer dual ftp/http protocol services, so we can avoid the exceptions by specifying in the URL to use http protocol. But it would be better if the code used an FTP client which had proper support for passive mode file transfers such as org.apache.commons.net.ftp.FTPClient.

Example of the error as observed:

[SHELL] Weekly Update: Create deleted list
java.io.IOException: sun.net.ftp.FtpProtocolException: PORT 172,18,233,39,194,100:500 Illegal command, EPSV ALL in effect.

```
at sun.net.www.protocol.ftp.FtpURLConnection.getInputStream(FtpURLConnection.java:488)
at org.cbioportal.pdb_annotation.scripts.PdbScriptsPipelineRunCommand.readFTPfile2List(PdbScriptsPipelineRunCommand.java:348)
at org.cbioportal.pdb_annotation.scripts.PdbScriptsPipelineRunCommand.prepareUpdatePDBFile(PdbScriptsPipelineRunCommand.java:404)
at org.cbioportal.pdb_annotation.scripts.PdbScriptsPipelineRunCommand.runUpdatePDB(PdbScriptsPipelineRunCommand.java:484)
at org.cbioportal.pdb_annotation.scripts.PdbScriptsPipelineStarter.main(PdbScriptsPipelineStarter.java:123)
```

(local machine on wireless network was assigned IP address 172.18.233.39)

**Comment by juexinwang** [comment]
Get stack in this:

**Comment by sheridancbio** [comment]
We decided to push this to "Low Priority" status

**Comment by juexinwang** [comment]
I changed all ftp:// to http:// it seems work on my linux version. Please check it on Mac System

**Comment by sheridancbio** [comment]
http: downloads are working on mac. Still, the "bug" is present if someone decides to point their machine at an ftp:: resource for download in the application.properties file. I will leave this issue open with low priority, but unassign it for now. We can get back to this in the future if we have time.

**Comment by acongy** [comment]
hello，I also encountered how to solve the problem
